sonar.projectKey=modul3-251511029
sonar.projectName=Modul 3 - 029 - Rizky Yanuar Irawan
sonar.sources=app,routes,resources
sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,public/build/**
sonar.sourceEncoding=UTF-8
